//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2014-09-12 12:51:35 by 懒惰的肥兔
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{    

    public class ShopNum1_Product
    {
        
        /// <summary>
        /// 
        /// </summary>        
        public Guid Guid { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string Name { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string OriginalImge { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string ThumbImage { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string SmallImage { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string RepertoryNumber { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public decimal Weight { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int RepertoryCount { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string UnitName { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int RepertoryAlertCount { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int PresentScore { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int PresentRankScore { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int SocreIntegral { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int LimitBuyCount { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public decimal CostPrice { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public decimal MarketPrice { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public decimal ShopPrice { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string Brief { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string Memo { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string Detail { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int ClickCount { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int CollectCount { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int BuyCount { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int CommentCount { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int ReferCount { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int IsSaled { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int IsBest { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int IsNew { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int IsHot { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int IsRecommend { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int IsReal { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int IsOnlySaled { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string Title { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string Description { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string Keywords { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int OrderID { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public Guid? SupplierGuid { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public Guid? BrandGuid { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string BrandName { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? ProductCategoryID { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public Guid? ProductTypeGuid { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string CreateUser { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public DateTime CreateTime { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string ModifyUser { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public DateTime ModifyTime { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int IsDeleted { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int SaleNumber { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int IsDownLoad { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string AgentID { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? IsAudit { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int IsRight { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string AgentGroup { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string ProductLineGuid { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public decimal? PushMoney { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string SupplierLoginID { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public decimal? SupplierCostPrice { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? SupplierRepertoryCount { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public decimal? SupplierProvidePrice { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public decimal? RecommendedPrice { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? SupplierProductCategoryID { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? Supply { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? AccumulateSupply { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? SupplierInventory { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? IsSupplierProduct { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public DateTime? ApplyAuditTime { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public DateTime? AuditTime { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? ModifyEditState { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? ModifyDeleteState { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string RefusedReason { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string ActiveImage { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string InventoryArea { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public decimal? CId { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string ProductProp { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string MobileDetail { get; set; }
         
      
    }
}

